FROM python:3.5-slim

MAINTAINER HaiQuan "haiquan5396@gmail.com"

ENV BROKER_CLOUD localhost
ENV BROKER_FOG locahost

COPY Cloud/Forwarder/requirements.txt /app/requirements.txt

COPY Communicator /app/Communicator

COPY Logging/ /app/Logging

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY Cloud/Forwarder/Forwarder_Cloud_to_Fog.py /app

#RUN export PYTHONPATH=/app

CMD python3 Forwarder_Cloud_to_Fog.py ${BROKER_CLOUD} ${BROKER_FOG}

#docker build -t haiquan5396/forwarder_cloud_to_fog:1.2 -f Dockerfile_Cloud_to_Fog .
